# Generated by Django 4.0.2 on 2022-04-04 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.SmallIntegerField()),
                ('approaches', models.SmallIntegerField()),
                ('repetition', models.SmallIntegerField()),
                ('muscle_category', models.CharField(choices=[('грудь', 'грудь'), ('спина', 'спина'), ('ноги', 'ноги'), ('плечи', 'плечи'), ('руки', 'руки')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_mark', models.SmallIntegerField()),
                ('a', models.CharField(max_length=255)),
                ('exercises', models.ManyToManyField(related_name='trainings', to='main.Exercise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
