# Generated by Django 4.0.2 on 2022-04-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_training_user_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='a',
        ),
    ]
