# Generated by Django 4.0.4 on 2022-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exercise_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='popularity',
            field=models.BigIntegerField(default=0, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_private',
            field=models.BooleanField(verbose_name='Приватное'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainings', to='main.exercise'),
        ),
    ]
