# Generated by Django 4.0.4 on 2022-05-12 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_exercise_popularity_alter_exercise_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ManyToManyField(null=True, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
