# Generated by Django 4.0.4 on 2022-05-12 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_exercise_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_favorite',
        ),
        migrations.CreateModel(
            name='UserExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.ManyToManyField(blank=True, null=True, to='main.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
